(defpackage #:raw-cffi-tcl9
  (:use #:cl)
  (:nicknames :raw-tcl9 :rctcl9 :raw-tcl)
  (:import-from #:cffi
   :define-foreign-library
   :use-foreign-library
   :with-foreign-objects
   :defcfun
   :defctype
   :defcenum
   :defcstruct
   :foreign-slot-value)
  (:export
   #:libtcl

   #:+NUM-STATIC-TOKENS+

   #:+TCL-ALL-EVENTS+
   #:+TCL-ALLOW-INLINE-COMPILATION+
   #:+TCL-ALPHA-RELEASE+
   #:+TCL-APPEND-VALUE+
   #:+TCL-ARGV-CONSTANT+
   #:+TCL-ARGV-END+
   #:+TCL-ARGV-FLOAT+
   #:+TCL-ARGV-FUNC+
   #:+TCL-ARGV-GENFUNC+
   #:+TCL-ARGV-HELP+
   #:+TCL-ARGV-INT+
   #:+TCL-ARGV-REST+
   #:+TCL-ARGV-STRING+
   #:+TCL-AUTO-LENGTH+

   #:+TCL-BETA-RELEASE+
   #:+TCL-BREAK+

   #:+TCL-CANCEL-UNWIND+
   #:+TCL-CHANNEL-THREAD-INSERT+
   #:+TCL-CHANNEL-THREAD-REMOVE+
   #:+TCL-CHANNEL-VERSION-1+
   #:+TCL-CHANNEL-VERSION-2+
   #:+TCL-CHANNEL-VERSION-3+
   #:+TCL-CHANNEL-VERSION-4+
   #:+TCL-CHANNEL-VERSION-5+
   #:+TCL-CLOSE-READ+
   #:+TCL-CLOSE-WRITE+
   #:+TCL-CLOSE2PROC+
   #:+TCL-CODE-USER-MAX+
   #:+TCL-CODE-USER-MIN+
   #:+TCL-COMBINE+
   #:+TCL-CONTINUE+
   #:+TCL-CONVERT-MULTIBYTE+
   #:+TCL-CONVERT-NOSPACE+
   #:+TCL-CONVERT-SYNTAX+
   #:+TCL-CONVERT-UNKNOWN+
   #:+TCL-CREATE-HARD-LINK+
   #:+TCL-CREATE-SYMBOLIC-LINK+
   #:+TCL-CUSTOM-PTR-KEYS+
   #:+TCL-CUSTOM-TYPE-KEYS+

   #:+TCL-D-STRING-STATIC-SIZE+
   #:+TCL-DONT-QUOTE-HASH+
   #:+TCL-DONT-USE-BRACES+
   #:+TCL-DONT-WAIT+
   #:+TCL-DOUBLE-SPACE+
   #:+TCL-DYNAMIC+

   #:+TCL-ENCODING-CHAR-LIMIT+
   #:+TCL-ENCODING-END+
   #:+TCL-ENCODING-INTERNAL-USE-MASK+
   #:+TCL-ENCODING-NO-TERMINATE+
   #:+TCL-ENCODING-PROFILE-REPLACE+
   #:+TCL-ENCODING-PROFILE-STRICT+
   #:+TCL-ENCODING-PROFILE-TCL8+
   #:+TCL-ENCODING-START+
   #:+TCL-ENCODING-STOPONERROR+
   #:+TCL-ENFORCE-MODE+
   #:+TCL-ENSEMBLE-PREFIX+
   #:+TCL-ERROR+
   #:+TCL-EVAL-DIRECT+
   #:+TCL-EVAL-GLOBAL+
   #:+TCL-EVAL-INVOKE+
   #:+TCL-EVAL-NOERR+
   #:+TCL-EXACT+
   #:+TCL-EXCEPTION+

   #:+TCL-F-OK+
   #:+TCL-FILE-EVENTS+
   #:+TCL-FILESYSTEM-VERSION-1+
   #:+TCL-FINAL-RELEASE+

   #:+TCL-GLOB-PERM-HIDDEN+
   #:+TCL-GLOB-PERM-R+
   #:+TCL-GLOB-PERM-RONLY+
   #:+TCL-GLOB-PERM-W+
   #:+TCL-GLOB-PERM-X+
   #:+TCL-GLOB-TYPE-BLOCK+
   #:+TCL-GLOB-TYPE-CHAR+
   #:+TCL-GLOB-TYPE-DIR+
   #:+TCL-GLOB-TYPE-FILE+
   #:+TCL-GLOB-TYPE-LINK+
   #:+TCL-GLOB-TYPE-MOUNT+
   #:+TCL-GLOB-TYPE-PIPE+
   #:+TCL-GLOB-TYPE-SOCK+
   #:+TCL-GLOBAL-ONLY+

   #:+TCL-HASH-KEY-DIRECT-COMPARE+
   #:+TCL-HASH-KEY-RANDOMIZE-HASH+
   #:+TCL-HASH-KEY-SYSTEM-HASH+
   #:+TCL-HASH-KEY-TYPE-VERSION+

   #:+TCL-IDLE-EVENTS+
   #:+TCL-INDEX-NONE+
   #:+TCL-INDEX-TEMP-TABLE+
   #:+TCL-INTEGER-SPACE+
   #:+TCL-INTERP-DESTROYED+
   #:+TCL-IO-FAILURE+

   #:+TCL-LEAVE-ERR-MSG+
   #:+TCL-LIMIT-COMMANDS+
   #:+TCL-LIMIT-TIME+
   #:+TCL-LINK-BOOLEAN+
   #:+TCL-LINK-CHAR+
   #:+TCL-LINK-DOUBLE+
   #:+TCL-LINK-FLOAT+
   #:+TCL-LINK-INT+
   #:+TCL-LINK-LONG+
   #:+TCL-LINK-READ-ONLY+
   #:+TCL-LINK-SHORT+
   #:+TCL-LINK-STRING+
   #:+TCL-LINK-UCHAR+
   #:+TCL-LINK-UINT+
   #:+TCL-LINK-ULONG+
   #:+TCL-LINK-USHORT+
   #:+TCL-LINK-WIDE-INT+
   #:+TCL-LINK-WIDE-UINT+
   #:+TCL-LIST-ELEMENT+
   #:+TCL-LOAD-GLOBAL+
   #:+TCL-LOAD-LAZY+

   #:+TCL-MATCH-NOCASE+
   #:+TCL-MAX-PREC+
   #:+TCL-MODE-BLOCKING+
   #:+TCL-MODE-NONBLOCKING+

   #:+TCL-NAMESPACE-ONLY+
   #:+TCL-NO-EVAL+
   #:+TCL-NULL-OK+
   #:+TCL-NUMBER-BIG+
   #:+TCL-NUMBER-DOUBLE+
   #:+TCL-NUMBER-INT+
   #:+TCL-NUMBER-NAN+

   #:+TCL-OK+
   #:+TCL-ONE-WORD-KEYS+

   #:+TCL-PARSE-BAD-NUMBER+
   #:+TCL-PARSE-BRACE-EXTRA+
   #:+TCL-PARSE-MISSING-BRACE+
   #:+TCL-PARSE-MISSING-BRACKET+
   #:+TCL-PARSE-MISSING-PAREN+
   #:+TCL-PARSE-MISSING-QUOTE+
   #:+TCL-PARSE-MISSING-VAR-BRACE+
   #:+TCL-PARSE-QUOTE-EXTRA+
   #:+TCL-PARSE-SUCCESS+
   #:+TCL-PARSE-SYNTAX+

   #:+TCL-R-OK+
   #:+TCL-READABLE+
   #:+TCL-REG-ADVANCED+
   #:+TCL-REG-ADVF+
   #:+TCL-REG-BASIC+
   #:+TCL-REG-CANMATCH+
   #:+TCL-REG-EXPANDED+
   #:+TCL-REG-EXTENDED+
   #:+TCL-REG-NEWLINE+
   #:+TCL-REG-NLANCH+
   #:+TCL-REG-NLSTOP+
   #:+TCL-REG-NOCASE+
   #:+TCL-REG-NOSUB+
   #:+TCL-REG-NOTBOL+
   #:+TCL-REG-NOTEOL+
   #:+TCL-REG-QUOTE+
   #:+TCL-RESULT-SIZE+
   #:+TCL-RETURN+

   #:+TCL-SERVICE-ALL+
   #:+TCL-SERVICE-NONE+
   #:+TCL-SMALL-HASH-TABLE+
   #:+TCL-STATIC+
   #:+TCL-STDERR+
   #:+TCL-STDIN+
   #:+TCL-STDOUT+
   #:+TCL-STRING-KEYS+
   #:+TCL-STUB-MAGIC+
   #:+TCL-SUBST-ALL+
   #:+TCL-SUBST-BACKSLASHES+
   #:+TCL-SUBST-COMMANDS+
   #:+TCL-SUBST-VARIABLES+

   #:+TCL-TCPSERVER-REUSEADDR+
   #:+TCL-TCPSERVER-REUSEPORT+
   #:+TCL-THREAD-JOINABLE+
   #:+TCL-THREAD-NOFLAGS+
   #:+TCL-THREAD-STACK-DEFAULT+
   #:+TCL-TIMER-EVENTS+
   #:+TCL-TOKEN-BS+
   #:+TCL-TOKEN-COMMAND+
   #:+TCL-TOKEN-EXPAND-WORD+
   #:+TCL-TOKEN-OPERATOR+
   #:+TCL-TOKEN-SIMPLE-WORD+
   #:+TCL-TOKEN-SUB-EXPR+
   #:+TCL-TOKEN-TEXT+
   #:+TCL-TOKEN-VARIABLE+
   #:+TCL-TOKEN-WORD+
   #:+TCL-TRACE-ARRAY+
   #:+TCL-TRACE-DELETE+
   #:+TCL-TRACE-DESTROYED+
   #:+TCL-TRACE-OLD-STYLE+
   #:+TCL-TRACE-READS+
   #:+TCL-TRACE-RENAME+
   #:+TCL-TRACE-RESULT-DYNAMIC+
   #:+TCL-TRACE-RESULT-OBJECT+
   #:+TCL-TRACE-UNSETS+
   #:+TCL-TRACE-WRITES+

   #:+TCL-UNLOAD-DETACH-FROM-INTERPRETER+
   #:+TCL-UNLOAD-DETACH-FROM-PROCESS+
   #:+TCL-UTF-MAX+

   #:+TCL-VOLATILE+

   #:+TCL-W-OK+
   #:+TCL-WINDOW-EVENTS+
   #:+TCL-WRITABLE+

   #:+TCL-X-OK+

   #:+TCL-ZLIB-COMPRESS-BEST+
   #:+TCL-ZLIB-COMPRESS-DEFAULT+
   #:+TCL-ZLIB-COMPRESS-FAST+
   #:+TCL-ZLIB-COMPRESS-NONE+
   #:+TCL-ZLIB-FINALIZE+
   #:+TCL-ZLIB-FLUSH+
   #:+TCL-ZLIB-FORMAT-AUTO+
   #:+TCL-ZLIB-FORMAT-GZIP+
   #:+TCL-ZLIB-FORMAT-RAW+
   #:+TCL-ZLIB-FORMAT-ZLIB+
   #:+TCL-ZLIB-FULLFLUSH+
   #:+TCL-ZLIB-NO-FLUSH+
   #:+TCL-ZLIB-STREAM-DEFLATE+
   #:+TCL-ZLIB-STREAM-INFLATE+

   #:tcl-main-ex
   #:tcl-pkg-init-stubs-check
   #:tcl-init-subsystems
   #:tcl-get-memory-info
   #:tcl-find-executable
   #:tcl-set-pre-init-script
   #:tcl-set-panic-proc
   #:tcl-static-library
   #:tcl-set-obj-name-of-executable
   #:fix-argv0

   #:TCL-ACCESS
   #:TCL-ADD-ERROR-INFO
   #:TCL-ADD-OBJ-ERROR-INFO
   #:TCL-ALERT-NOTIFIER
   #:TCL-ALERT-NOTIFIER-PROC
   #:TCL-ALLOC
   #:TCL-ALLOC-HASH-ENTRY-PROC
   #:TCL-ALLOC-STAT-BUF
   #:TCL-ALLOW-EXCEPTIONS
   #:TCL-APP-INIT-PROC
   #:TCL-APPEND-ALL-OBJ-TYPES
   #:TCL-APPEND-ELEMENT
   #:TCL-APPEND-EXPORT-LIST
   #:TCL-APPEND-FORMAT-TO-OBJ
   #:TCL-APPEND-LIMITED-TO-OBJ
   #:TCL-APPEND-OBJ-TO-ERROR-INFO
   #:TCL-APPEND-OBJ-TO-OBJ
   #:TCL-APPEND-PRINTF-TO-OBJ
   #:TCL-APPEND-RESULT
   #:TCL-APPEND-STRINGS-TO-OBJ
   #:TCL-APPEND-TO-OBJ
   #:TCL-APPEND-UNICODE-TO-OBJ
   #:TCL-ARGV-INFO
   #:TCL-ARGV-INFO-PTR
   #:TCL-ARGV-INFO-TCLASS
   #:TCL-ASYNC-CREATE
   #:TCL-ASYNC-DELETE
   #:TCL-ASYNC-HANDLER
   #:TCL-ASYNC-INVOKE
   #:TCL-ASYNC-MARK
   #:TCL-ASYNC-MARK-FROM-SIGNAL
   #:TCL-ASYNC-PROC
   #:TCL-ASYNC-READY
   #:TCL-ATTEMPT-ALLOC
   #:TCL-ATTEMPT-DB-CKALLOC
   #:TCL-ATTEMPT-DB-CKREALLOC
   #:TCL-ATTEMPT-REALLOC
   #:TCL-ATTEMPT-SET-OBJ-LENGTH

   #:TCL-BACKGROUND-ERROR
   #:TCL-BACKGROUND-EXCEPTION
   #:TCL-BAD-CHANNEL-OPTION
   #:TCL-BOUNCE-REF-COUNT

   #:TCL-CALL-FRAME
   #:TCL-CALL-FRAME-TCLASS
   #:TCL-CALL-WHEN-DELETED
   #:TCL-CANCEL-EVAL
   #:TCL-CANCEL-IDLE-CALL
   #:TCL-CANCELED

   #:TCL-CHANNEL
   #:TCL-CHANNEL-BLOCK-MODE-PROC
   #:TCL-CHANNEL-BUFFERED
   #:TCL-CHANNEL-CLOSE2-PROC
   #:TCL-CHANNEL-FLUSH-PROC
   #:TCL-CHANNEL-GET-HANDLE-PROC
   #:TCL-CHANNEL-GET-OPTION-PROC
   #:TCL-CHANNEL-HANDLER-PROC
   #:TCL-CHANNEL-INPUT-PROC
   #:TCL-CHANNEL-NAME
   #:TCL-CHANNEL-OUTPUT-PROC
   #:TCL-CHANNEL-PROC
   #:TCL-CHANNEL-SET-OPTION-PROC
   #:TCL-CHANNEL-THREAD-ACTION-PROC
   #:TCL-CHANNEL-TRUNCATE-PROC
   #:TCL-CHANNEL-TYPE
   #:TCL-CHANNEL-TYPE-PTR
   #:TCL-CHANNEL-TYPE-TCLASS
   #:TCL-CHANNEL-TYPE-VERSION
   #:TCL-CHANNEL-VERSION
   #:TCL-CHANNEL-WATCH-PROC
   #:TCL-CHANNEL-WIDE-SEEK-PROC

   #:type-name
   #:version
   #:close-proc
   #:input-proc
   #:output-proc
   #:seek-proc
   #:set-option-proc
   #:get-option-proc
   #:watch-proc
   #:get-handle-proc
   #:close2-proc
   #:block-mode-proc
   #:flush-proc
   #:handler-proc
   #:wide-seek-proc
   #:thread-action-proc
   #:truncate-proc

   #:TCL-CHAR16-LEN
   #:TCL-CHAR16-TO-UTF-D-STRING
   #:TCL-CHDIR
   #:TCL-CLEAR-CHANNEL-HANDLERS
   #:TCL-CLOSE
   #:TCL-CLOSE-EX
   #:TCL-CLOSE-PROC
   #:TCL-CMD-DELETE-PROC
   #:TCL-CMD-INFO
   #:TCL-CMD-INFO-PTR
   #:TCL-CMD-INFO-TCLASS
   #:TCL-CMD-OBJ-TRACE-DELETE-PROC
   #:TCL-CMD-OBJ-TRACE-PROC
   #:TCL-CMD-OBJ-TRACE-PROC2
   #:TCL-CMD-PROC
   #:TCL-CMD-TRACE-PROC
   #:TCL-COMMAND
   #:TCL-COMMAND-COMPLETE
   #:TCL-COMMAND-TRACE-INFO
   #:TCL-COMMAND-TRACE-PROC
   #:TCL-COMPARE-HASH-KEYS-PROC
   #:TCL-CONCAT
   #:TCL-CONCAT-OBJ
   #:TCL-CONDITION-FINALIZE
   #:TCL-CONDITION-NOTIFY
   #:TCL-CONDITION-PTR
   #:TCL-CONDITION-WAIT
   #:TCL-CONFIG
   #:TCL-CONFIG-PTR
   #:TCL-CONFIG-TCLASS
   #:TCL-CONSOLE-PANIC

   #:TCL-CONVERT-COUNTER-ELEMENT
   #:TCL-CONVERT-ELEMENT
   #:TCL-CONVERT-TO-TYPE

   #:TCL-CREATE-ALIAS
   #:TCL-CREATE-ALIAS-OBJ
   #:TCL-CREATE-CHANNEL
   #:TCL-CREATE-CHANNEL-HANDLER
   #:TCL-CREATE-CHILD
   #:TCL-CREATE-CLOSE-HANDLER
   #:TCL-CREATE-COMMAND
   #:TCL-CREATE-ENCODING
   #:TCL-CREATE-ENSEMBLE
   #:TCL-CREATE-EVENT-SOURCE
   #:TCL-CREATE-EXIT-HANDLER
   #:TCL-CREATE-FILE-HANDLER
   #:TCL-CREATE-FILE-HANDLER-PROC
   #:TCL-CREATE-INTERP
   #:TCL-CREATE-INTERP*
   #:TCL-CREATE-NAMESPACE
   #:TCL-CREATE-OBJ-COMMAND
   #:TCL-CREATE-OBJ-COMMAND2
   #:TCL-CREATE-OBJ-TRACE
   #:TCL-CREATE-OBJ-TRACE2
   #:TCL-CREATE-PIPE
   #:TCL-CREATE-THREAD
   #:TCL-CREATE-THREAD-EXIT-HANDLER
   #:TCL-CREATE-TIMER-HANDLER
   #:TCL-CREATE-TRACE

   #:TCL-CUT-CHANNEL

   #:TCL-D-STRING
   #:TCL-D-STRING-APPEND
   #:TCL-D-STRING-APPEND-ELEMENT
   #:TCL-D-STRING-END-SUBLIST
   #:TCL-D-STRING-FREE
   #:TCL-D-STRING-GET-RESULT
   #:TCL-D-STRING-INIT
   #:TCL-D-STRING-PTR
   #:TCL-D-STRING-RESULT
   #:TCL-D-STRING-SET-LENGTH
   #:TCL-D-STRING-START-SUBLIST
   #:TCL-D-STRING-TCLASS
   #:TCL-D-STRING-TO-OBJ

   #:TCL-DB-CKALLOC
   #:TCL-DB-CKFREE
   #:TCL-DB-CKREALLOC
   #:TCL-DB-DECR-REF-COUNT
   #:TCL-DB-INCR-REF-COUNT
   #:TCL-DB-IS-SHARED
   #:TCL-DB-NEW-BIGNUM-OBJ
   #:TCL-DB-NEW-BOOLEAN-OBJ
   #:TCL-DB-NEW-BYTE-ARRAY-OBJ
   #:TCL-DB-NEW-DICT-OBJ
   #:TCL-DB-NEW-DOUBLE-OBJ
   #:TCL-DB-NEW-LIST-OBJ
   #:TCL-DB-NEW-LONG-OBJ
   #:TCL-DB-NEW-OBJ
   #:TCL-DB-NEW-STRING-OBJ
   #:TCL-DB-NEW-WIDE-INT-OBJ

   #:TCL-DECR-REF-COUNT
   #:TCL-DECR-REF-COUNT*

   #:TCL-DELETE-ASSOC-DATA
   #:TCL-DELETE-CHANNEL-HANDLER
   #:TCL-DELETE-CLOSE-HANDLER
   #:TCL-DELETE-COMMAND
   #:TCL-DELETE-COMMAND-FROM-TOKEN
   #:TCL-DELETE-EVENT-SOURCE
   #:TCL-DELETE-EVENTS
   #:TCL-DELETE-EXIT-HANDLER
   #:TCL-DELETE-FILE-HANDLER
   #:TCL-DELETE-FILE-HANDLER-PROC
   #:TCL-DELETE-HASH-ENTRY
   #:TCL-DELETE-HASH-TABLE
   #:TCL-DELETE-INTERP
   #:TCL-DELETE-INTERP*
   #:TCL-DELETE-NAMESPACE
   #:TCL-DELETE-THREAD-EXIT-HANDLER
   #:TCL-DELETE-TIMER-HANDLER
   #:TCL-DELETE-TRACE

   #:TCL-DETACH-CHANNEL
   #:TCL-DETACH-PIDS

   #:TCL-DICT
   #:TCL-DICT-OBJ-DONE
   #:TCL-DICT-OBJ-FIRST
   #:TCL-DICT-OBJ-GET
   #:TCL-DICT-OBJ-NEXT
   #:TCL-DICT-OBJ-PUT
   #:TCL-DICT-OBJ-PUT-KEY-LIST
   #:TCL-DICT-OBJ-REMOVE
   #:TCL-DICT-OBJ-REMOVE-KEY-LIST
   #:TCL-DICT-OBJ-SIZE
   #:TCL-DICT-PTR
   #:TCL-DICT-SEARCH
   #:TCL-DICT-SEARCH-PTR
   #:TCL-DICT-SEARCH-TCLASS

   #:TCL-DISCARD-INTERP-STATE

   #:TCL-DO-ONE-EVENT
   #:TCL-DO-WHEN-IDLE

   #:TCL-DONT-CALL-WHEN-DELETED

   #:TCL-DRIVER-BLOCK-MODE-PROC
   #:TCL-DRIVER-CLOSE-PROC
   #:TCL-DRIVER-CLOSE2-PROC
   #:TCL-DRIVER-FLUSH-PROC
   #:TCL-DRIVER-GET-HANDLE-PROC
   #:TCL-DRIVER-GET-OPTION-PROC
   #:TCL-DRIVER-HANDLER-PROC
   #:TCL-DRIVER-INPUT-PROC
   #:TCL-DRIVER-OUTPUT-PROC
   #:TCL-DRIVER-SEEK-PROC
   #:TCL-DRIVER-SET-OPTION-PROC
   #:TCL-DRIVER-THREAD-ACTION-PROC
   #:TCL-DRIVER-TRUNCATE-PROC
   #:TCL-DRIVER-WATCH-PROC
   #:TCL-DRIVER-WIDE-SEEK-PROC

   #:TCL-DUMP-ACTIVE-MEMORY

   #:TCL-DUP-INTERNAL-REP-PROC

   #:TCL-DUPLICATE-OBJ

   #:TCL-ENCODING
   #:TCL-ENCODING-CONVERT-PROC
   #:TCL-ENCODING-FREE-PROC
   #:TCL-ENCODING-PTR
   #:TCL-ENCODING-STATE-PTR
   #:TCL-ENCODING-TYPE
   #:TCL-ENCODING-TYPE-PTR
   #:TCL-ENCODING-TYPE-TCLASS

   #:TCL-EOF

   #:TCL-ERRNO-ID
   #:TCL-ERRNO-MSG

   #:TCL-EVAL
   #:TCL-EVAL*
   #:TCL-EVAL-EX
   #:TCL-EVAL-EX*
   #:TCL-EVAL-FILE
   #:TCL-EVAL-OBJ
   #:TCL-EVAL-OBJ-EX
   #:TCL-EVAL-OBJV
   #:TCL-EVAL-TOKENS-STANDARD

   #:TCL-EVENT
   #:TCL-EVENT-CHECK-PROC
   #:TCL-EVENT-DELETE-PROC
   #:TCL-EVENT-PROC
   #:TCL-EVENT-PTR
   #:TCL-EVENT-SETUP-PROC
   #:TCL-EVENT-TCLASS
   #:TCL-EVENTUALLY-FREE

   #:TCL-EXIT
   #:TCL-EXIT-PROC
   #:TCL-EXIT-THREAD

   #:TCL-EXPORT

   #:TCL-EXPOSE-COMMAND

   #:TCL-EXPR-BOOLEAN
   #:TCL-EXPR-BOOLEAN-OBJ
   #:TCL-EXPR-DOUBLE
   #:TCL-EXPR-DOUBLE-OBJ
   #:TCL-EXPR-LONG
   #:TCL-EXPR-LONG-OBJ
   #:TCL-EXPR-OBJ
   #:TCL-EXPR-STRING

   #:TCL-EXTERNAL-TO-UTF
   #:TCL-EXTERNAL-TO-UTF-D-STRING
   #:TCL-EXTERNAL-TO-UTF-D-STRING-EX

   #:TCL-FETCH-INTERNAL-REP

   #:TCL-FILE-FREE-PROC
   #:TCL-FILE-PROC

   #:TCL-FILESYSTEM
   #:TCL-FILESYSTEM-PTR
   #:TCL-FILESYSTEM-TCLASS

   #:TCL-FINALIZE
   #:TCL-FINALIZE-NOTIFIER
   #:TCL-FINALIZE-NOTIFIER-PROC
   #:TCL-FINALIZE-THREAD

   #:TCL-FIND-COMMAND
   #:TCL-FIND-ENSEMBLE
   #:TCL-FIND-NAMESPACE
   #:TCL-FIND-SYMBOL

   #:TCL-FIRST-HASH-ENTRY

   #:TCL-FLUSH

   #:TCL-FORGET-IMPORT

   #:TCL-FORMAT

   #:TCL-FREE
   #:TCL-FREE-ENCODING
   #:TCL-FREE-HASH-ENTRY-PROC
   #:TCL-FREE-INTERNAL-REP
   #:TCL-FREE-INTERNAL-REP-PROC
   #:TCL-FREE-OBJ
   #:TCL-FREE-PARSE
   #:TCL-FREE-PROC

   #:TCL-FS-ACCESS
   #:TCL-FS-ACCESS-PROC
   #:TCL-FS-CHDIR
   #:TCL-FS-CHDIR-PROC
   #:TCL-FS-CONVERT-TO-PATH-TYPE
   #:TCL-FS-COPY-DIRECTORY
   #:TCL-FS-COPY-DIRECTORY-PROC
   #:TCL-FS-COPY-FILE
   #:TCL-FS-COPY-FILE-PROC
   #:TCL-FS-CREATE-DIRECTORY-PROC
   #:TCL-FS-CREATE-INTERNAL-REP-PROC
   #:TCL-FS-DATA
   #:TCL-FS-DELETE-FILE
   #:TCL-FS-DELETE-FILE-PROC
   #:TCL-FS-DUP-INTERNAL-REP-PROC
   #:TCL-FS-EQUAL-PATHS
   #:TCL-FS-EVAL-FILE
   #:TCL-FS-EVAL-FILE-EX
   #:TCL-FS-FILE-ATTR-STRINGS
   #:TCL-FS-FILE-ATTR-STRINGS-PROC
   #:TCL-FS-FILE-ATTRS-GET
   #:TCL-FS-FILE-ATTRS-GET-PROC
   #:TCL-FS-FILE-ATTRS-SET
   #:TCL-FS-FILE-ATTRS-SET-PROC
   #:TCL-FS-FILE-SYSTEM-INFO
   #:TCL-FS-FILESYSTEM-PATH-TYPE-PROC
   #:TCL-FS-FILESYSTEM-SEPARATOR-PROC
   #:TCL-FS-FREE-INTERNAL-REP-PROC
   #:TCL-FS-GET-CWD
   #:TCL-FS-GET-CWD-PROC
   #:TCL-FS-GET-FILE-SYSTEM-FOR-PATH
   #:TCL-FS-GET-INTERNAL-REP
   #:TCL-FS-GET-NATIVE-PATH
   #:TCL-FS-GET-NORMALIZED-PATH
   #:TCL-FS-GET-PATH-TYPE
   #:TCL-FS-GET-TRANSLATED-PATH
   #:TCL-FS-GET-TRANSLATED-STRING-PATH
   #:TCL-FS-INTERNAL-TO-NORMALIZED-PROC
   #:TCL-FS-JOIN-PATH
   #:TCL-FS-JOIN-TO-PATH
   #:TCL-FS-LINK
   #:TCL-FS-LINK-PROC
   #:TCL-FS-LIST-VOLUMES
   #:TCL-FS-LIST-VOLUMES-PROC
   #:TCL-FS-LOAD-FILE
   #:TCL-FS-LOAD-FILE-PROC
   #:TCL-FS-LSTAT
   #:TCL-FS-LSTAT-PROC
   #:TCL-FS-MATCH-IN-DIRECTORY
   #:TCL-FS-MATCH-IN-DIRECTORY-PROC
   #:TCL-FS-MOUNTS-CHANGED
   #:TCL-FS-NEW-NATIVE-PATH
   #:TCL-FS-NORMALIZE-PATH-PROC
   #:TCL-FS-OPEN-FILE-CHANNEL
   #:TCL-FS-OPEN-FILE-CHANNEL-PROC
   #:TCL-FS-PATH-IN-FILESYSTEM-PROC
   #:TCL-FS-PATH-SEPARATOR
   #:TCL-FS-REGISTER
   #:TCL-FS-REMOVE-DIRECTORY
   #:TCL-FS-REMOVE-DIRECTORY-PROC
   #:TCL-FS-RENAME-FILE
   #:TCL-FS-RENAME-FILE-PROC
   #:TCL-FS-SPLIT-PATH
   #:TCL-FS-STAT
   #:TCL-FS-STAT-PROC
   #:TCL-FS-TILDE-EXPAND
   #:TCL-FS-UNLOAD-FILE
   #:TCL-FS-UNLOAD-FILE-PROC
   #:TCL-FS-UNREGISTER
   #:TCL-FS-UTIME
   #:TCL-FS-UTIME-PROC
   #:TCL-FS-VERSION

   #:TCL-GET-ACCESS-TIME-FROM-STAT
   #:TCL-GET-ALIAS-OBJ
   #:TCL-GET-ALLOC-MUTEX
   #:TCL-GET-ASSOC-DATA
   #:TCL-GET-BIGNUM-FROM-OBJ
   #:TCL-GET-BLOCK-SIZE-FROM-STAT
   #:TCL-GET-BLOCKS-FROM-STAT
   #:TCL-GET-BOOL
   #:TCL-GET-BOOL-FROM-OBJ
   #:TCL-GET-BOOLEAN
   #:TCL-GET-BOOLEAN-FROM-OBJ
   #:TCL-GET-BYTE-ARRAY-FROM-OBJ
   #:TCL-GET-BYTES-FROM-OBJ
   #:TCL-GET-CHANGE-TIME-FROM-STAT

   #:TCL-GET-CHANNEL
   #:TCL-GET-CHANNEL-BUFFER-SIZE
   #:TCL-GET-CHANNEL-ERROR
   #:TCL-GET-CHANNEL-ERROR-INTERP
   #:TCL-GET-CHANNEL-HANDLE
   #:TCL-GET-CHANNEL-INSTANCE-DATA
   #:TCL-GET-CHANNEL-MODE
   #:TCL-GET-CHANNEL-NAME
   #:TCL-GET-CHANNEL-NAMES
   #:TCL-GET-CHANNEL-NAMES-EX
   #:TCL-GET-CHANNEL-OPTION
   #:TCL-GET-CHANNEL-THREAD
   #:TCL-GET-CHANNEL-TYPE

   #:TCL-GET-CHAR-LENGTH
   #:TCL-GET-CHILD
   #:TCL-GET-COMMAND-FROM-OBJ
   #:TCL-GET-COMMAND-FULL-NAME
   #:TCL-GET-COMMAND-INFO
   #:TCL-GET-COMMAND-INFO-FROM-TOKEN
   #:TCL-GET-COMMAND-NAME
   #:TCL-GET-CURRENT-NAMESPACE
   #:TCL-GET-CURRENT-THREAD
   #:TCL-GET-CWD
   #:TCL-GET-DEVICE-TYPE-FROM-STAT

   #:TCL-GET-DOUBLE
   #:TCL-GET-DOUBLE-FROM-OBJ

   #:TCL-GET-ENCODING
   #:TCL-GET-ENCODING-FROM-OBJ
   #:TCL-GET-ENCODING-NAME
   #:TCL-GET-ENCODING-NAME-FROM-ENVIRONMENT
   #:TCL-GET-ENCODING-NAMES
   #:TCL-GET-ENCODING-NUL-LENGTH
   #:TCL-GET-ENCODING-SEARCH-PATH

   #:TCL-GET-ENSEMBLE-FLAGS
   #:TCL-GET-ENSEMBLE-MAPPING-DICT
   #:TCL-GET-ENSEMBLE-NAMESPACE
   #:TCL-GET-ENSEMBLE-PARAMETER-LIST
   #:TCL-GET-ENSEMBLE-SUBCOMMAND-LIST
   #:TCL-GET-ENSEMBLE-UNKNOWN-HANDLER

   #:TCL-GET-ERRNO
   #:TCL-GET-ERROR-LINE

   #:TCL-GET-FS-DEVICE-FROM-STAT
   #:TCL-GET-FS-INODE-FROM-STAT

   #:TCL-GET-GLOBAL-NAMESPACE
   #:TCL-GET-GROUP-ID-FROM-STAT
   #:TCL-GET-HOST-NAME
   #:TCL-GET-INDEX-FROM-OBJ
   #:TCL-GET-INDEX-FROM-OBJ-STRUCT
   #:TCL-GET-INT
   #:TCL-GET-INT-FOR-INDEX
   #:TCL-GET-INT-FROM-OBJ
   #:TCL-GET-INTERP-PATH
   #:TCL-GET-LINK-COUNT-FROM-STAT
   #:TCL-GET-LONG-FROM-OBJ
   #:TCL-GET-MODE-FROM-STAT
   #:TCL-GET-MODIFICATION-TIME-FROM-STAT
   #:TCL-GET-NAME-OF-EXECUTALBLE
   #:TCL-GET-NAMESPACE-UNKNOWN-HANDLER
   #:TCL-GET-NUMBER
   #:TCL-GET-NUMBER-FROM-OBJ
   #:TCL-GET-OBJ-RESULT
   #:TCL-GET-OBJ-TYPE
   #:TCL-GET-OPEN-FILE
   #:TCL-GET-PARENT
   #:TCL-GET-PATH-TYPE
   #:TCL-GET-RANGE
   #:TCL-GET-REG-EXP-FROM-OBJ
   #:TCL-GET-RETURN-OPTIONS
   #:TCL-GET-SERVICE-MODE
   #:TCL-GET-SIZE-FROM-STAT
   #:TCL-GET-SIZE-INT-FROM-OBJ
   #:TCL-GET-STACKED-CHANNEL
   #:TCL-GET-STARTUP-SCRIPT
   #:TCL-GET-STD-CHANNEL
   #:TCL-GET-STRING
   #:TCL-GET-STRING-FROM-OBJ
   #:TCL-GET-STRING-RESULT
   #:TCL-GET-THREAD-DATA
   #:TCL-GET-TIME
   #:TCL-GET-TIME-PROC
   #:TCL-GET-TOP-CHANNEL

   #:TCL-GET-UNI-CHAR
   #:TCL-GET-UNICODE
   #:TCL-GET-UNICODE-FROM-OBJ

   #:TCL-GET-USER-ID-FROM-STAT

   #:TCL-GET-VAR
   #:TCL-GET-VAR*
   #:TCL-GET-VAR2
   #:TCL-GET-VAR2*
   #:TCL-GET-VAR2-EX

   #:TCL-GET-VERSION

   #:TCL-GET-WIDE-INT-FROM-OBJ
   #:TCL-GET-WIDE-U-INT-FROM-OBJ

   #:TCL-GETS
   #:TCL-GETS-OBJ

   #:TCL-GLOB-TYPE-DATA
   #:TCL-GLOB-TYPE-DATA-PTR
   #:TCL-GLOB-TYPE-DATA-TCLASS

   #:TCL-GLOBAL-EVAL
   #:TCL-GLOBAL-EVAL-OBJ

   #:TCL-HAS-STRING-REP

   #:TCL-HASH-ENTRY
   #:TCL-HASH-ENTRY-PTR
   #:TCL-HASH-ENTRY-TCLASS
   #:TCL-HASH-ENTRY/KEY
   #:TCL-HASH-KEY-PROC
   #:TCL-HASH-KEY-TYPE
   #:TCL-HASH-KEY-TYPE-PTR
   #:TCL-HASH-KEY-TYPE-TCLASS
   #:TCL-HASH-SEARCH
   #:TCL-HASH-SEARCH-PTR
   #:TCL-HASH-SEARCH-TCLASS
   #:TCL-HASH-STATS
   #:TCL-HASH-TABLE
   #:TCL-HASH-TABLE-PTR
   #:TCL-HASH-TABLE-TCLASS
   #:TCL-HASH-TYPE

   #:TCL-HIDE-COMMAND
   #:TCL-IDLE-PROC

   #:TCL-IMPORT

   #:TCL-INCR-REF-COUNT
   #:TCL-INCR-REF-COUNT*

   #:TCL-INIT
   #:TCL-INIT*
   #:TCL-INIT-BIGNUM-FROM-DOUBLE
   #:TCL-INIT-CUSTOM-HASH-TABLE
   #:TCL-INIT-HASH-TABLE
   #:TCL-INIT-MEMORY
   #:TCL-INIT-NOTIFIER
   #:TCL-INIT-NOTIFIER-PROC
   #:TCL-INIT-OBJ-HASH-TABLE
   #:TCL-INIT-STRING-REP
   #:TCL-INIT-STUB-TABLE
   #:TCL-INIT-STUBS

   #:TCL-INPUT-BLOCKED
   #:TCL-INPUT-BUFFERED

   #:TCL-INTERP-ACTIVE
   #:TCL-INTERP-DELETE-PROC
   #:TCL-INTERP-DELETED
   #:TCL-INTERP-PTR
   #:TCL-INTERP-STATE

   #:TCL-INVALIDATE-STRING-REP

   #:TCL-IS-CHANNEL-EXISTING
   #:TCL-IS-CHANNEL-REGISTERED
   #:TCL-IS-CHANNEL-SHARED
   #:TCL-IS-ENSEMBLE
   #:TCL-IS-SAFE
   #:TCL-IS-SHARED
   #:TCL-IS-SHARED*
   #:TCL-IS-STANDARD-CHANNEL

   #:TCL-JOIN-PATH
   #:TCL-JOIN-THREAD

   #:TCL-LIBRARY-INIT-PROC
   #:TCL-LIBRARY-UNLOAD-PROC

   #:TCL-LIMIT-ADD-HANDLER
   #:TCL-LIMIT-CHECK
   #:TCL-LIMIT-EXCEEDED
   #:TCL-LIMIT-GET-COMMANDS
   #:TCL-LIMIT-GET-GRANULARITY
   #:TCL-LIMIT-GET-TIME
   #:TCL-LIMIT-HANDLER-DELETE-PROC
   #:TCL-LIMIT-HANDLER-PROC
   #:TCL-LIMIT-READY
   #:TCL-LIMIT-REMOVE-HANDLER
   #:TCL-LIMIT-SET-COMMANDS
   #:TCL-LIMIT-SET-GRANULARITY
   #:TCL-LIMIT-SET-TIME
   #:TCL-LIMIT-TYPE-ENABLED
   #:TCL-LIMIT-TYPE-EXCEEDED
   #:TCL-LIMIT-TYPE-RESET
   #:TCL-LIMIT-TYPE-SET

   #:TCL-LINK-ARRAY
   #:TCL-LINK-VAR

   #:TCL-LIST-OBJ-APPEND-ELEMENT
   #:TCL-LIST-OBJ-APPEND-LIST
   #:TCL-LIST-OBJ-GET-ELEMENTS
   #:TCL-LIST-OBJ-INDEX
   #:TCL-LIST-OBJ-LENGTH
   #:TCL-LIST-OBJ-REPLACE

   #:TCL-LOAD-FILE
   #:TCL-LOAD-HANDLE
   #:TCL-LOAD-HANDLE-PTR

   #:TCL-LOG-COMMAND-INFO

   #:TCL-MAIN-LOOP-PROC
   #:TCL-MAKE-FILE-CHANNEL
   #:TCL-MAKE-TCP-CLIENT-CHANNEL

   #:TCL-MATH-PROC

   #:TCL-MERGE

   #:TCL-MUTEX-FINALIZE
   #:TCL-MUTEX-LOCK
   #:TCL-MUTEX-PTR
   #:TCL-MUTEX-UNLOCK

   #:TCL-NAMESPACE
   #:TCL-NAMESPACE-DELETE-PROC
   #:TCL-NAMESPACE-PTR
   #:TCL-NAMESPACE-TCLASS

   #:TCL-NEW-BIGNUM-OBJ
   #:TCL-NEW-BOOLEAN-OBJ
   #:TCL-NEW-BYTE-ARRAY-OBJ
   #:TCL-NEW-DICT-OBJ
   #:TCL-NEW-DOUBLE-OBJ
   #:TCL-NEW-INT-OBJ
   #:TCL-NEW-LIST-OBJ
   #:TCL-NEW-LONG-OBJ
   #:TCL-NEW-OBJ
   #:TCL-NEW-STRING-OBJ
   #:TCL-NEW-UNICODE-OBJ
   #:TCL-NEW-WIDE-INT-OBJ
   #:TCL-NEW-WIDE-U-INT-OBJ
   #:TCL-NEXT-HASH-ENTRY

   #:TCL-NOTIFIER-PROCS
   #:TCL-NOTIFIER-PROCS-PTR
   #:TCL-NOTIFIER-PROCS-TCLASS
   #:TCL-NOTIFY-CHANNEL

   #:TCL-NR-ADD-CALLBACK
   #:TCL-NR-CALL-OBJ-PROC
   #:TCL-NR-CALL-OBJ-PROC2
   #:TCL-NR-CMD-SWAP
   #:TCL-NR-CREATE-COMMAND
   #:TCL-NR-CREATE-COMMAND2
   #:TCL-NR-EVAL-OBJ
   #:TCL-NR-EVAL-OBJV
   #:TCL-NR-EXPR-OBJ
   #:TCL-NR-POST-PROC
   #:TCL-NR-SUBST-OBJ
   #:TCL-NUM-UTF-CHARS

   #:TCL-OBJ
   #:TCL-OBJ-CMD-PROC
   #:TCL-OBJ-CMD-PROC2
   #:TCL-OBJ-GET-VAR2
   #:TCL-OBJ-INTERNAL-REP
   #:TCL-OBJ-INTERNAL-REP-PTR
   #:TCL-OBJ-INTERNAL-REP/PTR-AND-LONG-REP
   #:TCL-OBJ-INTERNAL-REP/PTR-AND-LONG-REP-TCLASS
   #:TCL-OBJ-INTERNAL-REP/PTR-AND-SIZE
   #:TCL-OBJ-INTERNAL-REP/PTR-AND-SIZE-TCLASS
   #:TCL-OBJ-INTERNAL-REP/TWO-PTR-VALUE
   #:TCL-OBJ-INTERNAL-REP/TWO-PTR-VALUE-TCLASS
   #:TCL-OBJ-PRINTF
   #:TCL-OBJ-PTR
   #:TCL-OBJ-SET-VAR2
   #:TCL-OBJ-TCLASS
   #:TCL-OBJ-TYPE
   #:TCL-OBJ-TYPE-GET-ELEMENTS
   #:TCL-OBJ-TYPE-IN-OPERATOR-PROC
   #:TCL-OBJ-TYPE-INDEX-PROC
   #:TCL-OBJ-TYPE-LENGTH-PROC
   #:TCL-OBJ-TYPE-PTR
   #:TCL-OBJ-TYPE-REPLACE-PROC
   #:TCL-OBJ-TYPE-REVERSE-PROC
   #:TCL-OBJ-TYPE-SET-ELEMENT
   #:TCL-OBJ-TYPE-SLICE-PROC
   #:TCL-OBJ-TYPE-TCLASS

   #:TCL-OPEN-COMMAND-CHANNEL
   #:TCL-OPEN-FILE-CHANNEL
   #:TCL-OPEN-TCP-CLIENT
   #:TCL-OPEN-TCP-SERVER
   #:TCL-OPEN-TCP-SERVER-EX

   #:TCL-OUTPUT-BUFFERED

   #:TCL-PACKAGE-INIT-PROC

   #:TCL-PANIC
   #:TCL-PANIC-PROC

   #:TCL-PARSE
   #:TCL-PARSE-ARGS-OBJV
   #:TCL-PARSE-BRACES
   #:TCL-PARSE-COMMAND
   #:TCL-PARSE-EXPR
   #:TCL-PARSE-PTR
   #:TCL-PARSE-QUOTED-STRING
   #:TCL-PARSE-TCLASS
   #:TCL-PARSE-VAR
   #:TCL-PARSE-VAR-NAME

   #:TCL-PATH-TYPE

   #:TCL-PID
   #:TCL-PID-PTR

   #:TCL-PKG-PRESENT
   #:TCL-PKG-PRESENT-EX
   #:TCL-PKG-PROVIDE
   #:TCL-PKG-PROVIDE-EX
   #:TCL-PKG-REQUIRE
   #:TCL-PKG-REQUIRE-EX
   #:TCL-PKG-REQUIRE-PROC

   #:TCL-POSIX-ERROR
   #:TCL-PRESERVE
   #:TCL-PRINT-DOUBLE
   #:TCL-PROC-OBJ-CMD
   #:TCL-PUT-ENV

   #:TCL-QUERY-TIME-PROC
   #:TCL-QUEUE-EVENT
   #:TCL-QUEUE-POSITION

   #:TCL-READ
   #:TCL-READ-CHARS
   #:TCL-READ-RAW

   #:TCL-REALLOC
   #:TCL-REAP-DETACHED-PROCS

   #:TCL-RECORD-AND-EVAL
   #:TCL-RECORD-AND-EVAL-OBJ

   #:TCL-REG-EXP
   #:TCL-REG-EXP-COMPILE
   #:TCL-REG-EXP-EXEC
   #:TCL-REG-EXP-EXEC-OBJ
   #:TCL-REG-EXP-GET-INFO
   #:TCL-REG-EXP-INDICES
   #:TCL-REG-EXP-INDICES-PTR
   #:TCL-REG-EXP-INDICES-TCLASS
   #:TCL-REG-EXP-INFO
   #:TCL-REG-EXP-INFO-PTR
   #:TCL-REG-EXP-INFO-TCLASS
   #:TCL-REG-EXP-MATCH
   #:TCL-REG-EXP-MATCH-OBJ
   #:TCL-REG-EXP-RANGE

   #:TCL-REGISTER-CHANNEL
   #:TCL-REGISTER-CONFIG
   #:TCL-REGISTER-OBJ-TYPE

   #:TCL-RELEASE
   #:TCL-REMOVE-CHANNEL-MODE
   #:TCL-RESET-RESULT
   #:TCL-RESTORE-INTERP-STATE

   #:TCL-SAVE-INTERP-STATE
   #:TCL-SAVED-RESULT-PTR

   #:TCL-SCALE-TIME-PROC

   #:TCL-SCAN-COUNTED-ELEMENT
   #:TCL-SCAN-ELEMENT

   #:TCL-SEEK

   #:TCL-SERVICE-ALL
   #:TCL-SERVICE-EVENT
   #:TCL-SERVICE-MODE-HOOK
   #:TCL-SERVICE-MODE-HOOK-PROC

   #:TCL-SET-ASSOC-DATA
   #:TCL-SET-BIGNUM-OBJ
   #:TCL-SET-BOOLEAN-OBJ
   #:TCL-SET-BYTE-ARRAY-LENGTH
   #:TCL-SET-BYTE-ARRAY-OBJ

   #:TCL-SET-CHANNEL-BUFFER-SIZE
   #:TCL-SET-CHANNEL-ERROR
   #:TCL-SET-CHANNEL-ERROR-INTERP
   #:TCL-SET-CHANNEL-OPTION

   #:TCL-SET-COMMAND-INFO
   #:TCL-SET-COMMAND-INFO-FROM-TOKEN

   #:TCL-SET-DOUBLE-OBJ
   #:TCL-SET-ENCODING-SEARCH-PATH

   #:TCL-SET-ENSEMBLE-FLAGS
   #:TCL-SET-ENSEMBLE-MAPPING-DICT
   #:TCL-SET-ENSEMBLE-PARAMETER-LIST
   #:TCL-SET-ENSEMBLE-SUBCOMMAND-LIST
   #:TCL-SET-ENSEMBLE-UNKNOWN-HANDLER

   #:TCL-SET-ERRNO
   #:TCL-SET-ERROR-CODE
   #:TCL-SET-ERROR-LINE

   #:TCL-SET-FROM-ANY-PROC
   #:TCL-SET-INT-OBJ
   #:TCL-SET-LIST-OBJ
   #:TCL-SET-LONG-OBJ
   #:TCL-SET-MAIN-LOOP
   #:TCL-SET-MAX-BLOCK-TIME
   #:TCL-SET-NAMESPACE-UNKNOWN-HANDLER
   #:TCL-SET-NOTIFIER
   #:TCL-SET-OBJ-ERROR-CODE
   #:TCL-SET-OBJ-LENGTH
   #:TCL-SET-OBJ-RESULT
   #:TCL-SET-RECURSION-LIMIT
   #:TCL-SET-RESULT
   #:TCL-SET-RETURN-OPTIONS
   #:TCL-SET-SERVICE-MODE
   #:TCL-SET-STARTUP-SCRIPT
   #:TCL-SET-STD-CHANNEL
   #:TCL-SET-STRING-OBJ
   #:TCL-SET-SYSTEM-ENCODING
   #:TCL-SET-TIME-PROC
   #:TCL-SET-TIMER
   #:TCL-SET-TIMER-PROC
   #:TCL-SET-UNICODE-OBJ
   #:TCL-SET-VAR
   #:TCL-SET-VAR2
   #:TCL-SET-VAR2-EX
   #:TCL-SET-WIDE-INT-OBJ
   #:TCL-SET-WIDE-U-INT-OBJ

   #:TCL-SIGNAL-ID
   #:TCL-SIGNAL-MSG

   #:TCL-SIZE
   #:TCL-SIZE-PTR

   #:TCL-SLEEP

   #:TCL-SOCKET
   #:TCL-SOURCE-RC-FILE

   #:TCL-SPLICE-CHANNEL
   #:TCL-SPLIT-LIST
   #:TCL-SPLIT-PATH

   #:TCL-STACK-CHANNEL

   #:TCL-STAT
   #:TCL-STAT-BUF-PTR

   #:TCL-STORE-INTERNAL-REP

   #:TCL-STRING-CASE-MATCH
   #:TCL-STRING-MATCH

   #:TCL-STUB-CALL

   #:TCL-SUBST-OBJ

   #:TCL-TAKE-BIGNUM-FROM-OBJ

   #:TCL-TCP-ACCEPT-PROC

   #:TCL-TELL

   #:TCL-THREAD-ALERT
   #:TCL-THREAD-CREATE-PROC
   #:TCL-THREAD-DATA-KEY-PTR
   #:TCL-THREAD-ID
   #:TCL-THREAD-ID-PTR
   #:TCL-THREAD-QUEUE-EVENT

   #:TCL-TIME
   #:TCL-TIME-PTR
   #:TCL-TIME-TCLASS
   #:TCL-TIMER-PROC
   #:TCL-TIMER-TOKEN

   #:TCL-TOKEN
   #:TCL-TOKEN-PTR
   #:TCL-TOKEN-TCLASS

   #:TCL-TOM-MATH-INITIALIZE-STUBS

   #:TCL-TRACE
   #:TCL-TRACE-COMMAND
   #:TCL-TRACE-VAR
   #:TCL-TRACE-VAR2
   #:TCL-TRANSFER-RESULT
   #:TCL-TRANSLATE-FILE-NAME
   #:TCL-TRUNCATE-CHANNEL

   #:TCL-UNGETS

   #:TCL-UNI-CHAR
   #:TCL-UNI-CHAR-AT-INDEX
   #:TCL-UNI-CHAR-IS-ALNUM
   #:TCL-UNI-CHAR-IS-ALPHA
   #:TCL-UNI-CHAR-IS-CONTROL
   #:TCL-UNI-CHAR-IS-DIGIT
   #:TCL-UNI-CHAR-IS-GRAPH
   #:TCL-UNI-CHAR-IS-LOWER
   #:TCL-UNI-CHAR-IS-PRINT
   #:TCL-UNI-CHAR-IS-PUNCT
   #:TCL-UNI-CHAR-IS-SPACE
   #:TCL-UNI-CHAR-IS-UPPER
   #:TCL-UNI-CHAR-IS-WORD-CHAR
   #:TCL-UNI-CHAR-LEN
   #:TCL-UNI-CHAR-PTR
   #:TCL-UNI-CHAR-TO-LOWER
   #:TCL-UNI-CHAR-TO-TITLE
   #:TCL-UNI-CHAR-TO-UPPER
   #:TCL-UNI-CHAR-TO-UTF
   #:TCL-UNI-CHAR-TO-UTF-D-STRING

   #:TCL-UNLINK-VAR

   #:TCL-UNREGISTER-CHANNEL

   #:TCL-UNSET-VAR
   #:TCL-UNSET-VAR2

   #:TCL-UNSTACK-CHANNEL
   #:TCL-UNTRACE-COMMAND
   #:TCL-UNTRACE-VAR
   #:TCL-UNTRACE-VAR2
   #:TCL-UNUSED-STUB-ENTRY

   #:TCL-UP-VAR
   #:TCL-UP-VAR2

   #:TCL-UPDATE-LINKED-VAR
   #:TCL-UPDATE-STRING-PROC

   #:TCL-UTF-AT-INDEX
   #:TCL-UTF-BACKSLASH
   #:TCL-UTF-BACKSLASH*
   #:TCL-UTF-CHAR-COMPLETE
   #:TCL-UTF-FIND-FIRST
   #:TCL-UTF-FIND-LAST
   #:TCL-UTF-NCASECMP
   #:TCL-UTF-NCMP
   #:TCL-UTF-NEXT
   #:TCL-UTF-PREV
   #:TCL-UTF-TO-CHAR16
   #:TCL-UTF-TO-CHAR16-D-STRING
   #:TCL-UTF-TO-EXTERNAL
   #:TCL-UTF-TO-EXTERNAL-D-STRING
   #:TCL-UTF-TO-EXTERNAL-D-STRING-EX
   #:TCL-UTF-TO-LOWER
   #:TCL-UTF-TO-TITLE
   #:TCL-UTF-TO-UNI-CHAR
   #:TCL-UTF-TO-UNI-CHAR-D-STRING
   #:TCL-UTF-TO-UPPER

   #:TCL-VALIDATE-ALL-MEMORY

   #:TCL-VALUE-TYPE
   #:TCL-VALUE-TYPE-PTR

   #:TCL-VAR
   #:TCL-VAR-EVAL
   #:TCL-VAR-TRACE-INFO
   #:TCL-VAR-TRACE-INFO2
   #:TCL-VAR-TRACE-PROC

   #:TCL-WAIT-FOR-EVENT
   #:TCL-WAIT-FOR-EVENT-PROC
   #:TCL-WAIT-PID

   #:TCL-WIDE-INT
   #:TCL-WIDE-UINT

   #:TCL-WRITE
   #:TCL-WRITE-CHARS
   #:TCL-WRITE-OBJ
   #:TCL-WRITE-RAW

   #:TCL-WRONG-NUM-ARGS

   #:TCL-ZIPFS-MOUNT
   #:TCL-ZIPFS-MOUNT-BUFFER
   #:TCL-ZIPFS-TCL-LIBRARY
   #:TCL-ZIPFS-UNMOUNT

   #:TCL-ZLIB-ADLER32
   #:TCL-ZLIB-CRC32
   #:TCL-ZLIB-DEFLATE
   #:TCL-ZLIB-INFLATE
   #:TCL-ZLIB-STREAM-CHECKSUM
   #:TCL-ZLIB-STREAM-CLOSE
   #:TCL-ZLIB-STREAM-EOF
   #:TCL-ZLIB-STREAM-GET
   #:TCL-ZLIB-STREAM-GET-COMMAND-NAME
   #:TCL-ZLIB-STREAM-INIT
   #:TCL-ZLIB-STREAM-PTR
   #:TCL-ZLIB-STREAM-PUT
   #:TCL-ZLIB-STREAM-RESET
   #:TCL-ZLIB-STREAM-SET-COMPRESSION-DICTIONARY

   #:TCL_DICT-OBJ-SIZE
   #:TCL_FS-SPLIT-PATH
   #:TCL_FSCREATEDIRECTORY
   #:TCL_GET-ALIAS-OBJ
   #:TCL_GET-BYTES-FROM-OBJ
   #:TCL_GET-CHAR-LENGTH
   #:TCL_GET-RANGE
   #:TCL_GET-STRING-FROM-OBJ
   #:TCL_GET-UNI-CHAR
   #:TCL_GET-UNICODE-FROM-OBJ
   #:TCL_LIST-OBJ-GET-ELEMENTS
   #:TCL_LIST-OBJ-LENGTH
   #:TCL_NUM-UTF-CHARS
   #:TCL_PARSE-ARGS-OBJV
   #:TCL_SPLIT-LIST
   #:TCL_SPLIT-PATH
   #:TCL_UTF-AT-INDEX
   #:TCL_UTF-CHAR-COMPLETE
   #:TCL_UTF-NCASECMP
   #:TCL_UTF-NCMP
   #:TCL_UTF-NEXT
   #:TCL_UTF-PREV

   ))
